
debug: true
clone:
  path: github.com/drone/drone

build:
  image: drone/golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
  commands:
    - go get github.com/constabulary/gb/...
    - gb vendor restore
    - gb build

publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: quay.io/v1
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/acaleph/kube-alerts
    storage_driver: overlay
    file: Dockerfile