language: go

env:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=freebsd GIMME_ARCH=amd64

install:
  - go get github.com/constabulary/gb/...

script: make build

deploy:
  provider: releases
  api_key: "e80b88c33b8b268960ef764122808fb506aeec43"
  file_glob: true
  file:
    - bin/kube-alerts*
  skip_cleanup: true
  on:
    tags: true
